# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(error_messages={'unique': 'Esta tag já existe.'}, max_length=50, unique=True),
        ),
    ]
