# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20171201_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('local_file', models.FileField(upload_to='Media')),
                ('language', models.CharField(max_length=10)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Tag')),
            ],
        ),
    ]
